controllers:
    resource:
        path: ../src/Infrastructure/Controller/
        namespace: App\Infrastructure\Controller
    type: attribute

search_foods:
    path: /foods
    controller: App\Infrastructure\Controller\SearchController
    methods: GET

create_foods:
    path: /foods
    controller: App\Infrastructure\Controller\CreateController
    methods: POST